enums:
  side:
    - buy
    - sell

sources:
  live_pnl:
    primary_key: instrument_id
    columns:
      instrument_id: Integer
      symbol: String
      net_position: BigInt
      last_price: Float
      market_value: Float
      realized_pnl: Float
      unrealized_pnl: Float

  trades:
    primary_key: id
    columns:
      id: Integer
      instrument_id: Integer
      side: side
      quantity: Integer
      price: Float
      executed_at: Timestamp

  alerts:
    primary_key: id
    columns:
      id: Integer
      event_id: String
      timestamp: Timestamp
      trigger_name: String
      event_type: String
      data: JSON